### ISSUE TITLE
[Request] Update Goldhen Host for 7.55 FW

### ISSUE THREAD

**Issue by Kinho-Loureiro** [GoldHEN/GoldHEN#98] opened 2022-11-23 14:29 UTC
Dudes can you update Goldhen host FW7.55 for newest Goldhen 2.2.5v please? I wanna use the FPS counter and the new features.🙏

**Comment by kmeps4** [comment] 2023-01-03 19:07
I'll close this one since this is not a bug.. it's a request.
Will close it as no planned.

**Closed by kmeps4** 2023-01-03 19:07 UTC
