### ISSUE TITLE
Goldhen 9.00 can't dump games

### ISSUE THREAD

**Issue by wheelmac92** [GoldHEN/GoldHEN#5] opened 2021-12-15 13:29 UTC
Yup, it just can't

**Comment by SiSTR0** [comment] 2021-12-19 22:57
do you mean using embedded Binloader? try to use the 2.0b2 version

**Comment by RandQalan** [comment] 2021-12-20 01:47
Sorry but standard dump app is not working some has found a workaround but basic app dump not working.

**Comment by SiSTR0** [comment] 2021-12-20 05:06
I didn't understand if the problem is when the payload is launched via GoldHEN's embedded binloader. If so it was fixed in 2.0b2
If the problem is in general I can't do support on other dev payloads, wait for the author to make new updates if necessary.

**Closed by SiSTR0** 2021-12-20 05:06 UTC

**Comment by RandQalan** [comment] 2021-12-20 05:17
> I didn't understand if the problem is when the payload is launched via GoldHEN's embedded binloader. If so it was fixed in 2.0b2 If the problem is in general I can't do support on other dev payloads, wait for the author to make new updates if necessary.

It is working but only on GH2.0b with web expoit only haven't  tried yet with 2.0b2 _
